version: '3'
services:
  postgres:
    build: 
      context: ./postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: logins
    ports:
      - "5432:5432"
    networks:
      - weather_hub_network

  backend:
    build:
      context: ./server
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    networks:
      - weather_hub_network

  frontend:
    build:
      context: ./weather_hub
    ports:
      - "6000:3000"
    depends_on:
      - backend
    networks:
      - weather_hub_network
  
  nginx:
    build: 
      context: ./nginx
    restart: always
    tty: true
    ports: 
      - "8000:80"
    networks: 
      - weather_hub_network
    depends_on:
       - backend
       - frontend

networks:
  weather_hub_network:
    driver: bridge
